# Definition for singly-linked list.
# class ListNode(object):
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next

# class Solution(object):
#     def removeElements(self, head, val):

#         dummy = ListNode(0)
#         dummy.next = head

#         prev = dummy
#         curr = head

#         while curr is not None:

#             if curr.val == val:
#                 prev.next = curr.next
#             else:
#                 prev = curr

#             curr = curr.next

#         return dummy.next   

# Given the head of a singly linked list, return the middle node of the linked list.

# If there are two middle nodes, return the second middle node.

# class Solution(object):
#     def middleNode(self, head):
#         slow=head
#         fast=head
        
#         while(fast!=None and fast.next!=None):
           
#              slow=slow.next
#              fast=fast.next.next
#         return slow     

# Given head, the head of a linked list, determine if the linked list has a cycle in it.

# There is a cycle in a linked list if there is some node in the list that can be reached again by continuously following the next pointer. Internally, pos is used to denote the index of the node that tail's next pointer is connected to. Note that pos is not passed as a parameter.

# Return true if there is a cycle in the linked list. Otherwise, return false. 

# Definition for singly-linked list.
# class ListNode(object):
#     def __init__(self, x):
#         self.val = x
#         self.next = None

# class Solution(object):
#     def hasCycle(self, head):
#         slow=head
#         fast=head
#         while(fast!=None and fast.next!=None):
           
#                 fast=fast.next.next
#                 slow=slow.next
#                 if(fast==slow):
#                           return True
            
#         return False

#  Write an algorithm to determine if a number n is happy.

# A happy number is a number defined by the following process:

# Starting with any positive integer, replace the number by the sum of the squares of its digits.
# Repeat the process until the number equals 1 (where it will stay), or it loops endlessly in a cycle which does not include 1.
# Those numbers for which this process ends in 1 are happy.
# Return true if n is a happy number, and false if not.
 
class Solution(object):
    def nextno(self,n):
        total=0
        while n>0:
            
            digit=n%10
            total=total+digit*digit
            n=n//10
        return total
    
    def isHappy(self, n):
        slow=n
        fast=n
        while True:
             slow=self.nextno(slow)
             fast=self.nextno(self.nextno(fast))
             if (slow==1 or fast==1):
                 return True
             if(slow==fast):
                  return False
         
# There is a singly-linked list head and we want to delete a node node in it.

# You are given the node to be deleted node. You will not be given access to the first node of head.

# All the values of the linked list are unique, and it is guaranteed that the given node node is not the last node in the linked list.

# Delete the given node. Note that by deleting the node, we do not mean removing it from memory. We mean:

# The value of the given node should not exist in the linked list.
# The number of nodes in the linked list should decrease by one.
# All the values before node should be in the same order.
# All the values after node should be in the same order.  
# Definition for singly-linked list.
# class ListNode(object):
#     def __init__(self, x):
#         self.val = x
#         self.next = None
class Solution(object):
    def deleteNode(self, node):
        node.val = node.next.val
        node.next = node.next.next     
        
# Given the head of a singly linked list, reverse the list, and return the reversed list.
 
 # Definition for singly-linked list.
# class ListNode(object):
#     def __init__(self, val=0, next=None):
#         self.val = val
#         self.next = next
class Solution(object):
    def reverseList(self, head):
        prev=None
        curr=head
        next=None
        while curr is not None:
            next=curr.next
            curr.next=prev
            prev=curr
            curr=next
        return prev

# Given an integer x, return true if x is a palindrome, and false otherwise.

class Solution(object):
    def isPalindrome(self, x):
        temp=x
        sum=0
        if x<0:
            return False
        
        while temp!=0:
            digit=temp%10
            sum=sum*10+digit
            temp//=10
        
        if(temp==x):
            return True
        else:
            return False

# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

 class Solution(object):
    def findTheDifference(self, s, t):
        s = sorted(s)
        t = sorted(t)

        for i in range(len(s)):
            if s[i] != t[i]:
                return t[i]

        return t[-1]